export const letters1 = [
  { text: "Q", value: "q" },
  { text: "W", value: "w" },
  { text: "E", value: "e" },
  { text: "R", value: "r" },
  { text: "T", value: "t" },
  { text: "Y", value: "y" },
  { text: "U", value: "u" },
  { text: "I", value: "i" },
  { text: "O", value: "o" },
  { text: "P", value: "p" },
  { text: "[", value: "[", text2: "{", value2: "{" },
  { text: "]", value: "]", text2: "}", value2: "}" },
  { text: "\\", value: "\\", text2: "|", value2: "|" },
];

export const letters2 = [
  { text: "A", value: "a" },
  { text: "S", value: "s" },
  { text: "D", value: "d" },
  { text: "F", value: "f" },
  { text: "G", value: "g" },
  { text: "H", value: "h" },
  { text: "J", value: "j" },
  { text: "K", value: "k" },
  { text: "L", value: "l" },
  { text: ";", value: ";", text2: ":", value2: ":" },
  { text: "'", value: "'", text2: '"', value2: '"' },
];

export const letters3 = [
  { text: "Z", value: "z" },
  { text: "X", value: "x" },
  { text: "C", value: "c" },
  { text: "V", value: "v" },
  { text: "B", value: "b" },
  { text: "N", value: "n" },
  { text: "M", value: "m" },
  { text: ",", value: ",", text2: "<", value2: "<" },
  { text: ".", value: ".", text2: ">", value2: ">" },
  { text: "/", value: "/", text2: "?", value2: "?" },
];

export const numbers = [
  { text: "`", value: "`", text2: "~", value2: "~" },
  { text: "1", value: "1", text2: "!", value2: "!" },
  { text: "2", value: "2", text2: "@", value2: "@" },
  { text: "3", value: "3", text2: "#", value2: "#" },
  { text: "4", value: "4", text2: "$", value2: "$" },
  { text: "5", value: "5", text2: "%", value2: "%" },
  { text: "6", value: "6", text2: "^", value2: "^" },
  { text: "7", value: "7", text2: "&", value2: "&" },
  { text: "8", value: "8", text2: "*", value2: "*" },
  { text: "9", value: "9", text2: "(", value2: "(" },
  { text: "0", value: "0", text2: ")", value2: ")" },
  { text: "-", value: "-", text2: "_", value2: "_" },
  { text: "=", value: "=", text2: "+", value2: "+" },
];

export const specialCharacters = [
  "`",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "0",
  "-",
  "=",
  "[",
  "]",
  "\\",
  ";",
  "'",
  ",",
  ".",
  "/",
];
