export const letters1 = [
  { text: "Q", value: "q" },
  { text: "W", value: "w" },
  { text: "E", value: "e" },
  { text: "R", value: "r" },
  { text: "T", value: "t" },
  { text: "Y", value: "y" },
  { text: "U", value: "u" },
  { text: "I", value: "i" },
  { text: "O", value: "o" },
  { text: "P", value: "p" },
  { text: "[", value: "[", text2: "{", value2: "{" },
  { text: "]", value: "]", text2: "}", value2: "}" },
  { text: "\\", value: "\\", text2: "|", value2: "|" },
];

export const letters2 = [
  { text: "A", value: "a" },
  { text: "S", value: "s" },
  { text: "D", value: "d" },
  { text: "F", value: "f" },
  { text: "G", value: "g" },
  { text: "H", value: "h" },
  { text: "J", value: "j" },
  { text: "K", value: "k" },
  { text: "L", value: "l" },
  { text: ";", value: ";", text2: ":", value2: ":" },
  { text: "'", value: "'", text2: '"', value2: '"' },
];

export const letters3 = [
  { text: "Z", value: "z" },
  { text: "X", value: "x" },
  { text: "C", value: "c" },
  { text: "V", value: "v" },
  { text: "B", value: "b" },
  { text: "N", value: "n" },
  { text: "M", value: "m" },
  { text: ",", value: ",", text2: "<", value2: "<" },
  { text: ".", value: ".", text2: ">", value2: ">" },
  { text: "/", value: "/", text2: "?", value2: "?" },
];

export const numbers = [
  { text: "`", value: "`", text2: "~", value2: "~" },
  { text: "1", value: "1", text2: "!", value2: "!" },
  { text: "2", value: "2", text2: "@", value2: "@" },
  { text: "3", value: "3", text2: "#", value2: "#" },
  { text: "4", value: "4", text2: "$", value2: "$" },
  { text: "5", value: "5", text2: "%", value2: "%" },
  { text: "6", value: "6", text2: "^", value2: "^" },
  { text: "7", value: "7", text2: "&", value2: "&" },
  { text: "8", value: "8", text2: "*", value2: "*" },
  { text: "9", value: "9", text2: "(", value2: "(" },
  { text: "0", value: "0", text2: ")", value2: ")" },
  { text: "-", value: "-", text2: "_", value2: "_" },
  { text: "=", value: "=", text2: "+", value2: "+" },
];

export const specialCharacters = [
  "`",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "0",
  "-",
  "=",
  "[",
  "]",
  "\\",
  ";",
  "'",
  ",",
  ".",
  "/",
];

export const colours = [
  { colour: "copper", right: "60" },
  { colour: "green", right: "50" },
  { colour: "yellow", right: "40" },
  { colour: "blue", right: "30" },
  { colour: "purple", right: "20" },
  { colour: "white", right: "10" },
];

export const extraKeys = [
  {
    id: 0,
    name: "control",
    lgH: "12",
    mdH: "10",
    smH: "9",
    H: "6",
    lgW: "16",
    mdW: "12",
    smW: "10",
    W: "6",
    text: "ctrl",
  },
  {
    id: 1,
    name: "function",
    lgH: "12",
    mdH: "10",
    smH: "9",
    H: "6",
    lgW: "16",
    mdW: "12",
    smW: "10",
    W: "6",
    text: "fn",
  },
  {
    id: 2,
    name: "alt",
    lgH: "12",
    mdH: "10",
    smH: "9",
    H: "6",
    lgW: "16",
    mdW: "12",
    smW: "10",
    W: "6",
    text: "alt",
  },
  {
    id: 3,
    name: "spaceBar",
    lgH: "12",
    mdH: "10",
    smH: "9",
    H: "6",
    lgW: "82",
    mdW: "68",
    smW: "60",
    W: "18",
    text: "",
  },
  {
    id: 4,
    name: "left",
    lgH: "12",
    mdH: "10",
    smH: "9",
    H: "6",
    lgW: "12",
    mdW: "10",
    smW: "10",
    W: "6",
    text: "<",
  },
  {
    id: 5,
    name: "right",
    lgH: "12",
    mdH: "10",
    smH: "9",
    H: "6",
    lgW: "12",
    mdW: "10",
    smW: "10",
    W: "6",
    text: ">",
  },
  {
    id: 6,
    name: "up",
    lgH: "5",
    mdH: "4",
    smH: "3.5",
    H: "2.5",
    lgW: "12",
    mdW: "10",
    smW: "10",
    W: "6",
    text: "",
  },
  {
    id: 7,
    name: "backSpace",
    lgH: "12",
    mdH: "10",
    smH: "9",
    H: "6",
    lgW: "24",
    mdW: "22",
    smW: "20",
    W: "10",
    text: "backspace",
  },
  {
    id: 8,
    name: "tab",
    lgH: "12",
    mdH: "10",
    smH: "9",
    H: "6",
    lgW: "24",
    mdW: "22",
    smW: "20",
    W: "10",
    text: "tab",
  },
  {
    id: 9,
    name: "capslock",
    lgH: "12",
    mdH: "10",
    smH: "9",
    H: "6",
    lgW: "28",
    mdW: "22",
    smW: "20",
    W: "11",
    text: "caps lock",
  },
  {
    id: 10,
    name: "enter",
    lgH: "12",
    mdH: "10",
    smH: "9",
    H: "6",
    lgW: "24",
    mdW: "22",
    smW: "18",
    W: "8",
    text: "enter",
  },
  {
    id: 11,
    name: "shift",
    lgH: "12",
    mdH: "10",
    smH: "9",
    H: "6",
    lgW: "34",
    mdW: "26",
    smW: "24",
    W: "12",
    text: "shift",
  },
];
